### PR TITLE
Extend block types

### PR DESCRIPTION
**Pull request by rossberg**
This PR introduces local checking with extended block types, as discussed in #44.

Extends overview, interpreter, and test suite.

See diff to Overview.md for details.

### CODE REVIEW

**Comment by jakobkummerow** [comment]
It would be good if this could talk about exceptions/try-catch. While that's officially only a phase 3 proposal right now, it's [shipped](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Exception#browser_compatibility) in all major browsers, so as a matter of practice, any new proposals can't just ignore it. (Aside from EH being shipped, AFAIK all prospective users of typed-funcref/GC and NNLs are also using EH, so this isn't just a theoretical concern.)

Specifically, one question is whether the following should validate:
```
(try $x
  (; possibly some instructions that can't throw ;)
  (local.set $x ...)
  (call $maybe_throws)
  (; possibly more ;)
catch_all
  (; not touching $x here ;)
)
(local.get $x)
```
With as-precise-as-possible tracking of initialized-ness, this should validate. However, that requires (possibly prohibitively expensive) per-instruction validation overhead, because for every instruction in the `(; possibly some instructions that can't throw ;)` range, the engine would have to check whether that instruction can throw, in order to determine whether the `(local.set $x ...)` is guaranteed to be reached.
This overhead is why for "option 1c" in the large discussion thread, we made the decision to treat any `local.set` inside a `try`-block as "possibly not reached" (even if it is the very first instruction in the block); another way of phrasing that is that for purposes of locals initializedness tracking, "`try..catch` behaves like `if..else`".

A related question is whether the presence of the `catch_all` should make a difference. In theory, an entirely `catch`-less `try`-block could ignore any possibly-exception-throwing points for its locals initializedness tracking: if control flow makes it through the block without throwing, then all `local.set`s must have been executed. But that would mean that at the time a single-pass validator sees a `(local.set ...)` after something that can throw, it doesn't know yet whether there'll be a `catch_all` later or not, so it can't decide whether the variable should count as initialized after the block. Once again, the "treat `try..catch` like `if..else`" strategy solves the problem and keeps validation fast, but it's only one option of many, and it does pay a price for its simplicity and speed: it conservatively under-approximates initializedness of locals.

One way or another, this specification for "option 1b" should clarify how it wants `try`-blocks (with or without `catch $tag`, with or without `catch_all) to be handled.

**Comment by conrad-watt** [comment]
@jakobkummerow with the current `1b` pitch it will exactly work like you describe with the `if..else` approach - the set of initialised locals that `catch` sees is fixed at entry to the `try`. In addition to the point you made about potential validation slowdowns, It's tough to support reasoning about throws in the validation algorithm because we'd still have to overapproximate where they can happen (e.g. every `call`), so it's not clear how often producers would be able to take advantage of the extra expressiveness.

I don't have very meaningful thoughts on how to reflect this intention in @rossberg's interpreter prototype... maybe we could port `try...catch` blocks in just up to validation?

**Comment by jakobkummerow** [comment]
It would also be good to clarify whether the binary format for the list of initialized locals in a block type is allowed to contain duplicates (currently it's only spec'ed to be a `vec(u32)` AFAICS).
For implementations it's slightly more convenient if duplicates are disallowed, because then the size of the `vec(u32)` can immediately be used to allocate an array into which the `vec` will be decoded, and a `vec` with more entries than the current function has locals can be rejected as invalid right away. Obviously it's possible to de-dupe duplicates if they are allowed, that's just a bit more work.

**Comment by conrad-watt** [comment]
> For implementations it's slightly more convenient if duplicates are disallowed, because then the size of the `vec(u32)` can immediately be used to allocate an array into which the `vec` will be decoded, and a `vec` with more entries than the current function has locals can be rejected as invalid right away. Obviously it's possible to de-dupe duplicates if they are allowed, that's just a bit more work.

We could mandate no dupes, but then the implementation would actually have to check and enforce this - would this save work overall? It seems like the common case would be that a well-behaved producer doesn't actually emit any dupes.

Could the implementation allocate an array based on the size of the vec that may be "too big", and proceed with validation on the optimistic assumption that no dupes are present? If dupes are in fact present, maybe some redundant work is done during validation (i.e. some "init" flag gets set twice), but this keeps well-behaved producers from incurring the de-dupe cost.

**Comment by rossberg** [comment]
@jakobkummerow, fair enough, technically, the given validation rule for blocktypes already said it, but I added a note pointing it out in prose.

**Comment by conrad-watt** [comment]
@jakobkummerow ah, you've made me realise that my reply to you previously is misleading. The natural `1b` rule will mean that `catch`-less `try` will work like your second bullet point, unless I'm misunderstanding something (see below).

> a `catch`-less `try`-block would also be unable to initialize any locals, because it would pretend to have an empty `catch_all`-block

This surprises me - if a catch-all block is executed to completion, doesn't control then exit the end of the `try..catch` block normally? So `catch`less-`try` isn't equivalent to an empty `catch-all`, because the exception is never "rethrown"?

Note that with the rules @rossberg is proposing, a `try` of the shape `try... catch_all rethrow end` is permitted to initialise variables inside the `try` to be visible after the `end`, because the unconditional `rethrow` would be modelled as initialising all variables (since control never gets past it).

**Comment by jakobkummerow** [comment]
Sounds like we're in agreement then that `catch`-less `try` is like `block`. We actually do implement it as `try... catch_all rethrow end`, but that doesn't stand in the way of treating it like `block` as far as locals initialization is concerned.

**Comment by rossberg** [comment]
Closing this in favour of #63.

**Pull request closed without merging**
