### PR TITLE
Remove type annotations on ref.as_non_null and br_on_null

### PR DESCRIPTION
**Pull request by rossberg**
Following WebAssembly/reference-types#99 and addressing issue #27, this removes the type annotations from `ref.as_non_null` and `br_on_null` (they already were absent on `call_ref` and `func.bind`).

One small caveat is that this requires extending the bottom type to a bottom heap type, to be able to type an unknown reference type in an instruction output.

### CODE REVIEW

**Comment by lars-t-hansen** [comment]
Looks plausible.

**Comment by taralx** [comment]
> Wait, what bottom type?

Polymorphic type used when stack underflows in unreachable code.

**Comment by taralx** [comment]
Is `Ref(Bot, false)` just simpler to implement than `Bot`, or is there some other consideration?

**Comment by taralx** [comment]
(did anyone notice that `matches` is not symmetric w.r.t. `Bot`?)

**Comment by RossTate** [comment]
I can't find anything about a bottom type in the overview. Where should I look for more details about it?

**Comment by taralx** [comment]
If I understand the history correctly:

Added as `Unknown` in https://github.com/WebAssembly/reference-types/pull/3.
Renamed to `Bot` in https://github.com/WebAssembly/reference-types/pull/43.
Removed from reference-types along with subtyping in https://github.com/WebAssembly/reference-types/pull/87.

**Comment by RossTate** [comment]
Oh, `nullref`? But the current overview says `ref.null ht: [] -> [(ref null ht)]`. I'm confused.

**Comment by taralx** [comment]
No, not `nullref`. That's not polymorphic. There is no way to instantiate the bottom type in real code -- it is a placeholder that exists only during validation.

**Comment by RossTate** [comment]
Oh, I see. It’s not part of the spec; it’s just a device used in the reference implementation. Is that right?

**Comment by taralx** [comment]
I believe so, but I'll let @rossberg confirm.

**Comment by rossberg** [comment]
It will appear in the spec, but only as an internal type. You cannot use it in a program. Similar as with the [bottom value type](https://github.com/WebAssembly/function-references/blob/master/document/core/syntax/types.rst#value-types) that was previously in the reftypes proposal.

**Comment by rossberg** [comment]
@taralx:
> Is Ref(Bot, false) just simpler to implement than Bot, or is there some other consideration?

You'll need both. The latter matches any value type whatsoever, the former only reference types. When you have determined that an operand is a ref type you must not lose that information. Rules out
```
(unreachable)
(ref.as_non_null)
(i32.add)
```
(cf. [`unreached-invalid.wast`](https://github.com/WebAssembly/function-references/pull/31/files#diff-50d519994386eff0e48368f9077c36c2))

> (did anyone notice that matches is not symmetric w.r.t. Bot?)

It shouldn't be. It's a bottom type, not a top type.

**Comment by RossTate** [comment]
Got it. Thanks for the explanation!

**Comment by taralx** [comment]
LGTM, thanks!

**Pull request merged**
