### PR TITLE
Update binary encodings

### LINKED ISSUE #103: Binary encoding out of sync with GC proposal
After https://github.com/WebAssembly/gc/pull/372, the two repositories are out of sync regarding the binary encoding. Assuming that the GC proposal's patch is the source of truth now, this repository should be updated as follows:
- `0xd3` is reserved for `ref.eq`
- `ref.as_non_null` is `0xd4` (not d3)
- `br_on_null` is `0xd5` (not d4)
- `(ref ht)` is `-0x1c` (not -0x15)
- `(ref null ht)` is `-0x1d` (not -0x14)

### PR DESCRIPTION
**Pull request by tlively**
Update the encodings for ref.as_non_null, br_on_null, (ref ht), and (ref null ht) for consistency with the final encodings chosen in https://github.com/WebAssembly/gc/pull/372.

Fixes #103.

### CODE REVIEW

**Comment by tlively** [comment]
cc @jakobkummerow

**Comment by titzer** [comment]
Do you also want to update markdown overview?

**Comment by tlively** [comment]
Thanks, done.

**Review by Cctrip6g — APPROVED** [review]

**Review by Cctrip6g — APPROVED** [review]

**Review by rossberg — APPROVED** [review]
Great, thanks!

**Pull request merged**
